#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

// top_hmap kept without any transforms, so we could "retransform" it again
layout(r32f, binding = 0) uniform image2D hmap_sum;
layout(rgba32f, binding = 1) uniform readonly image2D mesh;

layout(location = 4) uniform mat4 inverse_transform;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(mesh);

    ivec2 halfsize = size / 2;
    // convert to [-1;1) , NOT, le'ts trye -32 to 32.0f asin Terrain.vert
    //TODO: use C++ matrix transformations instead
//    vec4 srcPos = inverse_transform * vec4(coord.x / 16.0f - 32.0f, 0.0f, coord.y / 16.0f - 32.0f, 1.0f);
//    ivec2 mesh_coord = ivec2((srcPos.x + 32.0f) * 16.0f, (srcPos.z + 32.0f) * 16.0f);

//    ivec2 mesh_coord = ivec2(srcPos.x, srcPos.z);
//    vec4 srcPos = inverse_transform * vec4(coord.x, 0.0f, coord.y, 1.0f);
//    ivec2 mesh_coord = ivec2(srcPos.x, srcPos.z);


    vec4 srcPos = inverse_transform * vec4(coord.x, 0.0f, coord.y, 1.0f);
//    ivec2 mesh_coord = ivec2((srcPos.x + 32.0f) * 16.0f, (srcPos.z + 32.0f) * 16.0f);
    ivec2 mesh_coord = ivec2(srcPos.xz);

    // convert back to [0;size)
    vec4 mesh_value = imageLoad(mesh, mesh_coord);

    // we've already wrapped it in FlattenPrep shader after transform
    float top_value = mesh_value.y;
    float bottom_value = imageLoad(hmap_sum, coord).r;

    float new_height = bottom_value + top_value;
    imageStore(hmap_sum, coord, vec4(new_height)); // clip to border
}
