#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

// top_hmap kept without any transforms, so we could "retransform" it again
layout(r32f, binding = 0) uniform image2D hmap_sum;
//layout(rgba32f, binding = 1) uniform readonly image2D mesh;
layout(r32f, binding = 1) uniform readonly image2D mesh;

layout(location = 4) uniform mat4 inverse_transform;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    float mesh_value = imageLoad(mesh, coord).r;
    float hmap_value = imageLoad(mesh, coord).r;
    float new_height = mesh_value + hmap_value;
    imageStore(hmap_sum, coord, vec4(mesh_value)); // clip to border
}
