#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(r32f, binding = 0) uniform readonly image2D hmap;
layout(r32f, binding = 1) uniform writeonly image2D mesh;

layout(location = 4) uniform mat4 inverse_transform;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outCoord = ivec2(gl_GlobalInvocationID.xy);

    vec2 worldPos = vec2(outCoord) - vec2(512.0);
    vec4 local = inverse_transform * vec4(worldPos.x, 0.0, worldPos.y, 1.0);

    ivec2 inCoord = ivec2(local.x + 512.0, local.z + 512.0);
    ivec2 size = imageSize(hmap);
    float inside =
      float(inCoord.x >= 0) * float(inCoord.y >= 0) *
      float(inCoord.x < size.x) * float(inCoord.y < size.y);

    float height = imageLoad(hmap, inCoord).r;
    imageStore(mesh, outCoord, vec4(height - inside * local.y / 32.0f));
}
