#version 460 core
layout (local_size_x = 8, local_size_y = 8) in;

layout (binding = 0, r32f) uniform readonly image2D height_map;
layout (binding = 1, rg8) uniform writeonly image2D normal_map;

uniform float height_scale = 1.0f;
uniform float texel_size = 1.0f;

void main() {
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(height_map);

    // Clamp edges
    float hN = imageLoad(height_map, clamp(id + ivec2(0, 1), ivec2(0), size - 1)).r;
    float hS = imageLoad(height_map, clamp(id + ivec2(0, -1), ivec2(0), size - 1)).r;
    float hE = imageLoad(height_map, clamp(id + ivec2(1, 0), ivec2(0), size - 1)).r;
    float hW = imageLoad(height_map, clamp(id + ivec2(-1, 0), ivec2(0), size - 1)).r;

    // World-space gradients
    vec3 dx = vec3(texel_size, 0.0, height_scale * (hE - hW));
    vec3 dy = vec3(0.0, texel_size, height_scale * (hN - hS));

    vec3 normal = normalize(cross(dx, dy));

    vec2 encodedNormal = normal.xy * 0.5 + 0.5;
    imageStore(normal_map, id, vec4(encodedNormal, 1.0, 1.0));
}
