#version 460 core

layout (local_size_x = 16, local_size_y = 16) in;

layout (r8, binding = 0) uniform readonly image2D mask;
layout (r8, binding = 1) uniform writeonly image2D mask_blured;

layout (location = 0) uniform float blur_factor; // radius (e.g., 1.0, 2.0, etc.)

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(mask);

    float sum = 0.0;
    float weight_sum = 0.0;

    // kernel radius in pixels
    int radius = int(blur_factor);
    radius = 1;

    for (int y = -radius; y <= radius; ++y) {
        for (int x = -radius; x <= radius; ++x) {
            ivec2 sample_coords = clamp(coords + ivec2(x, y), ivec2(0), size - ivec2(1));
            float sampl = imageLoad(mask, sample_coords).r;

        // simple uniform weight (box blur)
        float weight = 1.0;
        sum += sampl * weight;
        weight_sum += weight;
        }
    }

    float blured_value = sum / weight_sum;
    imageStore(mask_blured, coords, vec4(blured_value, 0.0, 0.0, 1.0));
}
//TODO: delete this