#version 460 core

layout (local_size_x = 16, local_size_y = 16) in;

layout (r32f, binding = 0) uniform image2D hmap;
layout (r8, binding = 1) uniform readonly image2D mask;

layout (location = 0) uniform float extra_height;
layout (location = 1) uniform float blur_factor;

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    float hmap_value = imageLoad(hmap, coords).r;
    float mask_value = imageLoad(mask, coords).r;

    ivec2 size = imageSize(mask);
    float sum = 0.0;
    int radius = int(blur_factor);
    float weight_sum = 0.0f;
//    ivec2 pseudo_random = ivec2(uint(coords.x) & 15, uint(coords.y) & 15);
    ivec2 pseudo_random = ivec2(0);
    for (int y = -radius; y <= radius; y = y + pseudo_random.y + 1) {
        for (int x = -radius; x <= radius; x = x + pseudo_random.x + 1) {
            ivec2 sample_coords = clamp(coords + ivec2(x, y), ivec2(0), size - ivec2(1));
            float sampl = imageLoad(mask, sample_coords).r;
            sum += sampl;
            ++weight_sum;
        }
    }
    float blured_mask_value = sum / weight_sum;
    float height = hmap_value + extra_height * blured_mask_value;
    imageStore(hmap, coords, vec4(height));
}


void foo() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    float hmap_value = imageLoad(hmap, coords).r;
    float mask_value = imageLoad(mask, coords).r; // TODO: taken wrt faloff factor
    float height = mix(hmap_value, extra_height, mask_value);

    ivec2 size = imageSize(mask);
    float sum = 0.0;
    float weight_sum = 0.0;
    int radius = int(blur_factor);
    radius = 10;
    for (int y = -radius; y <= radius; ++y) {
        for (int x = -radius; x <= radius; ++x) {
            ivec2 sample_coords = clamp(coords + ivec2(x, y), ivec2(0), size - ivec2(1));
            float sampl = imageLoad(mask, sample_coords).r;
            // simple uniform weight (box blur)
            float weight = 1.0;
            sum += sampl * weight;
            weight_sum += weight;
        }
    }
    float blured_value = sum / weight_sum;

    imageStore(hmap, coords, vec4(hmap_value + extra_height * blured_value));
}