#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, r8) uniform writeonly image2D tex_selection;
layout(binding = 1, r32ui) uniform readonly uimage2D fbo_tex;

layout(location = 0) uniform vec2 pointA;
layout(location = 1) uniform vec2 pointB;

layout(location = 2) uniform float radius;

float PointLineSegmentDistance(vec2 p, vec2 a, vec2 b) {
    vec2 ab = b - a;
    vec2 ap = p - a;
    float ab2 = dot(ab, ab);
    float t = dot(ap, ab) / ab2;
    t = clamp(t, 0.0, 1.0);
    vec2 nearestPoint = a + t * ab;
    return length(p - nearestPoint);
}

void main() {
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
    float distance = PointLineSegmentDistance(pixelCoord, pointA, pointB);
    if (distance <= radius * 450.0f) {
        uint fbo_value = imageLoad(fbo_tex, pixelCoord).r;
        imageStore(tex_selection, pixelCoord,
                   vec4(fbo_value, fbo_value, fbo_value, 1.0));
    }
}
