#version 460 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (binding = 0, r8) uniform readonly image2D height_map;
layout (binding = 1, rg8) uniform writeonly image2D normal_map;

void main() {
    uvec2 id = gl_GlobalInvocationID.xy;

    // Load height values around the current pixel
    float h0 = imageLoad(height_map, ivec2(id + uvec2(0, 1))).r;
    float h1 = imageLoad(height_map, ivec2(id + uvec2(0, -1))).r;
    float h2 = imageLoad(height_map, ivec2(id + uvec2(1, 0))).r;
    float h3 = imageLoad(height_map, ivec2(id + uvec2(-1, 0))).r;

    // Calculate the gradient vectors
    vec3 dx = vec3(1.0, 0.0, 16.0f * 16.0f * (h2 - h3));  // Difference in the x direction
    vec3 dy = vec3(0.0, 1.0, 16.0f * 16.0f * (h0 - h1));  // Difference in the y direction

    // Compute the normal by taking the cross product of the gradients
    vec3 normal = normalize(cross(dx, dy));

    // Write the normal to the normal map
    vec2 encodedNormal = normal.xy * 0.5 + 0.5;  // Encode the normal into RG8 format
//    encodedNormal.x = pow(encodedNormal.x, -4.0f);
//    encodedNormal.y = pow(encodedNormal.y, -4.0f);
    imageStore(normal_map, ivec2(id), vec4(encodedNormal, 0.0, 1.0));
}
