#version 460 core
layout(local_size_x = 256) in;

layout(std430, binding = 9) buffer Blades {
    vec4 pos[]; // xyz = position, w = phase
};

layout(location = 0) uniform float sin_time;
layout(location = 1) uniform float map_scale;

layout(std140, binding = 0) uniform Camera {
    vec3 pos;       float _pad0;
    vec3 forward;   float _pad1;
    vec3 right;     float _pad2;
    vec3 up;        float cos_half_fov;
    mat4 view;
    mat4 proj;
} camera;

layout(std140, binding = 4) uniform Player {
    vec3 pos;       float _pad0;
} player;

const float WORLD_MIN = -32.0;
const float WORLD_SIZE = 64.0;
const float CELL_FACTOR = 20.0;
const int GRID_SIZE = int(WORLD_SIZE * CELL_FACTOR); // 6400


ivec2 WorldToGrid(vec2 p) {
    // [-32,32) → [0,64)
    vec2 local = p - vec2(WORLD_MIN);
    // [0,64) → [0,6400)
    return ivec2(floor(local * CELL_FACTOR));
}

uint GridToID(ivec2 g) {
    // safety
    g = clamp(g, ivec2(0), ivec2(GRID_SIZE - 1));
    return uint(g.y * GRID_SIZE + g.x);
}

ivec2 LocalPattern(uint id) {
    int x = int(id % 32) - 8;   // -16 .. +15
    int z = int(id / 32) - 8;   // -16 .. +15
//    x *= x*x / 16;
//    z *= z*z / 16;
    return ivec2(x, z);
}
ivec2 LocalPattern2(uint id)
{
    vec2 uv = vec2(id % 32, id / 32) / 31.0;
    vec2 p  = uv * 2.0 - 1.0;

    float bias = 2.5;
    p = sign(p) * vec2(
    pow(abs(p.x), bias),
    pow(abs(p.y), bias)
    );
//    p = sign(p) * pow(abs(p), bias);

    return ivec2(round(p * 15.5));
}


void main() {
    const uint bladeCount = 512;
    uint id = gl_GlobalInvocationID.x;
    if (id >= bladeCount) return;

    ivec2 player_id = WorldToGrid(player.pos.xz);
    ivec2 grass_id = LocalPattern(id);
    ivec2 world_blade_id = player_id + grass_id;
    vec3 p = vec3(map_scale);
    p.x = float(world_blade_id.x) / CELL_FACTOR + WORLD_MIN;
    p.z = float(world_blade_id.y) / CELL_FACTOR + WORLD_MIN;

    float distance_to_player = float(length(grass_id / 16.0f));


/**

    vec3 camForward = normalize(-vec3(
    camera.view[0][2],
    camera.view[1][2],
    camera.view[2][2]
    ));

    vec3 toBlade = p - camera.pos / map_scale;
    float dist = length(toBlade);
    vec3 dir = toBlade / dist;

    float facing = dot(dir, camForward);
    float fovW = smoothstep(camera.cos_half_fov, 1.0, facing);
    float distW = exp(-dist * 0.15);

    float w = fovW * distW;

    facing = dot(normalize(p - camera.pos), camera.forward);*/

//    if (facing < camera.cos_half_fov) return;
    /**if (hash(id + seed) > w) {
        pos[id].xyz = vec3(1e6);
        return;
    }*/

    pos[id] = vec4(p.x, distance_to_player, p.z,
    float(id) / 100.0f + sin_time * float(id) / 200.0f); // phase = 0
}
