#version 460 core
layout (local_size_x = 8, local_size_y = 8) in;

layout (binding = 0, r32f) uniform readonly image2D tex_hmap;
layout (binding = 1, r32f) uniform readonly image2D tex_rivers_deform;
layout (binding = 2, r8) uniform readonly image2D tex_rivers_mask;
layout (binding = 3, r32f) uniform readonly image2D tex_roads_deform;
layout (binding = 4, r8) uniform readonly image2D tex_roads_mask;
layout (binding = 5, r8) uniform readonly image2D tex_slope;
layout (binding = 6, r32f) uniform writeonly image2D tex_result_hmap;
layout (binding = 7, r8) uniform writeonly image2D tex_result_mask;

void main() {
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    float height = imageLoad(tex_hmap, id).r;
    float rivers_deform = imageLoad(tex_rivers_deform, id).r;
    float river_mask = imageLoad(tex_rivers_mask, id).r;
    float road_deform = imageLoad(tex_roads_deform, id).r;
    float result_height = height + rivers_deform + road_deform * (1.0f - river_mask);
    imageStore(tex_result_hmap, id, vec4(result_height));

    float road_mask = imageLoad(tex_roads_mask, id).r;
    float slope_mask = imageLoad(tex_slope, id).r;
    float result_mask = max(max(river_mask, road_mask), slope_mask);
    result_mask = max(river_mask, road_mask);
    imageStore(tex_result_mask, id, vec4(result_mask));
}
