/**
#version 460 core

layout (location = 0) in vec2 in_position;
layout (location = 1) in vec2 in_texcoord;

// vec2 for position and a scale
layout (location = 2) in vec3 in_transform;
layout(location = 5) uniform float res_factor;

out vec2 texcoord;

//TODO: in case of non-squared sprites we need to keep ratio
// for this purpose we can follow this order:
// (assume we have't setup both coords and transforms)
// 1. generate/init transforms_1 based on coords_1 - vec2_scale
// 2. adjust vec2_translate & vec2_scale in transforms_1 doc
// 3. generate coords_1 based on transforms_1 doc
// -- then the most convenient way to do so is
//    is to setup vbo with 5 floats: vec2_translate, vec2_scale, scale_factor.
//    so now vec2_scale keeps the ration, while scale_factor is a custom param
//    that simply multiplied vec2_scale.
//    That's 5kb instead of 3kb - not a big of a deal...
// hold on. 4 floats: vec2_translate, ratio_w_on_h, scale;
// since we have rectangular shapes - relation w/y is enough

// for the first stage we can start not from coords_1, but
// from separate tex coord file, generated by ME or by other program(mine/Krita?)

// step1: we have coords -> find centre and accord. translate
// step2: now find how we got fro -1:1 to current - that's scale
// step3: look at texture coords - find ration
//TODO: but we also have to take into account TileTexture ratio...

//TODO: should i Write a program for tex atlas....

void main() {
    // we discard any pos at in_position simply ignoring it
    vec2 position = in_position;
//    vec2 position = vertices[gl_VertexID].xy;
    vec2 translate = vec2(in_transform[0], in_transform[1]);
    float scale = in_transform[2];
    // vec2(res_factor, 1.0f) is cur RESOLUTION factor
    position = position * scale * vec2(res_factor, 1.0f) + translate;
    gl_Position = vec4(position, -1.0f, 1.0f);
    texcoord = in_texcoord;
}
*/

#version 460 core
layout (location = 0) in vec2 in_position;
layout (location = 1) in vec2 in_texcoord;

layout(location = 3) uniform mat3 transform;
layout(location = 5) uniform float res_factor;

out vec2 texcoord;
/*
it's easier to hold transformations as vec3{translate.xy, scale}
so now we always apply transformations in correct order
*/

void main() {
    vec3 position = transform * vec3(in_position, 1.0f);
    gl_Position = vec4(position.xy, -1.0f, 1.0f);
    texcoord = in_texcoord;
}