#version 460 core
layout(local_size_x = 16, local_size_y = 16) in;
layout(r32f, binding = 0) uniform image2D bottom_layer;
layout(r32f, binding = 1) uniform readonly image2D top_layer;
layout(location = 2) uniform float strength;
void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size  = imageSize(bottom_layer);
    if (coord.x >= size.x || coord.y >= size.y)
    return;
    vec4 bottom = imageLoad(bottom_layer, coord);
    vec4 top    = imageLoad(top_layer, coord);
    vec4 result = bottom + top * strength;
    imageStore(bottom_layer, coord, result);
}
