#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(r32f, binding = 0) uniform image2D bottom_layer;
layout(r32f, binding = 1) uniform readonly image2D top_layer;

layout(location = 0) uniform bool invert;
//layout(location = 1) uniform bool tiling;
layout(location = 2) uniform float strength;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    float bottom = imageLoad(bottom_layer, coord).r;
    float top = imageLoad(top_layer, coord).r;
    int factor = invert ? -1 : 1;
    float result = bottom + top * strength * factor;
    imageStore(bottom_layer, coord, vec4(result));
}
