#version 460 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

//layout (location = 0) uniform uint Size;
layout (location = 3) uniform uint Step;
layout (location = 4) uniform bool PingPong;
layout (location = 9) uniform bool horizontal;

const float PI = 3.1415926;

layout (binding = 0, rgba32f) readonly uniform image2D PrecomputedData;
layout (binding = 1, rg32f) uniform image2D Buffer0;
layout (binding = 2, rg32f) uniform image2D Buffer1;

struct complex {
    float real;
    float im;
};

complex mul(complex c0, complex c1) {
    complex c;
    c.real = c0.real * c1.real - c0.im * c1.im;
    c.im = c0.real * c1.im + c0.im * c1.real;
    return c;
}

complex add(complex c0, complex c1) {
    complex c;
    c.real = c0.real + c1.real;
    c.im = c0.im + c1.im;
    return c;
}


void horizontalButterflies() {
    complex H;
    ivec2 x = ivec2(gl_GlobalInvocationID.xy);
    if (PingPong) {
        vec4 data = imageLoad(PrecomputedData, ivec2(Step, x.x)).rgba;
        vec2 p_ = imageLoad(Buffer0, ivec2(data.z, x.y)).rg;
        vec2 q_ = imageLoad(Buffer0, ivec2(data.w, x.y)).rg;
        vec2 w_ = vec2(data.x, data.y);

        complex p = complex(p_.x, p_.y);
        complex q = complex(q_.x, q_.y);
        complex w = complex(w_.x, w_.y);

        H = add(p, mul(w, q));
        imageStore(Buffer1, x, vec4(H.real, H.im, 0, 1));
    } else {
        vec4 data = imageLoad(PrecomputedData, ivec2(Step, x.x)).rgba;
        vec2 p_ = imageLoad(Buffer1, ivec2(data.z, x.y)).rg;
        vec2 q_ = imageLoad(Buffer1, ivec2(data.w, x.y)).rg;
        vec2 w_ = vec2(data.x, data.y);

        complex p = complex(p_.x, p_.y);
        complex q = complex(q_.x, q_.y);
        complex w = complex(w_.x, w_.y);

        H = add(p, mul(w, q));
        imageStore(Buffer0, x, vec4(H.real, H.im, 0, 1));
    }
}

void verticalButterflies() {
    complex H;
    ivec2 x = ivec2(gl_GlobalInvocationID.xy);
    if (PingPong) {
        vec4 data = imageLoad(PrecomputedData, ivec2(Step, x.y)).rgba;
        vec2 p_ = imageLoad(Buffer0, ivec2(x.x, data.z)).rg;
        vec2 q_ = imageLoad(Buffer0, ivec2(x.x, data.w)).rg;
        vec2 w_ = vec2(data.x, data.y);

        complex p = complex(p_.x, p_.y);
        complex q = complex(q_.x, q_.y);
        complex w = complex(w_.x, w_.y);

        H = add(p, mul(w, q));
        imageStore(Buffer1, x, vec4(H.real, H.im, 0, 1));
    } else {
        vec4 data = imageLoad(PrecomputedData, ivec2(Step, x.y)).rgba;
        vec2 p_ = imageLoad(Buffer1, ivec2(x.x, data.z)).rg;
        vec2 q_ = imageLoad(Buffer1, ivec2(x.x, data.w)).rg;
        vec2 w_ = vec2(data.x, data.y);

        complex p = complex(p_.x, p_.y);
        complex q = complex(q_.x, q_.y);
        complex w = complex(w_.x, w_.y);

        H = add(p, mul(w, q));
        imageStore(Buffer0, x, vec4(H.real, H.im, 0, 1));
    }
}

void main(void) {
    if (horizontal) {
        horizontalButterflies();
    } else {
        verticalButterflies();
    }
}
