#version 460 core

layout (local_size_x = 1, local_size_y = 16, local_size_z = 1) in;

layout (binding = 0, rgba32f) writeonly uniform image2D PrecomputeBuffer;

layout (std430, binding = 1) buffer indices {
    int j[];
} bit_reversed;

layout (location = 0) uniform uint Size;

const float PI = 3.1415926;

vec2 ComplexExp(vec2 a) {
    return vec2(cos(a.y), sin(a.y)) * exp(a.x);
}

struct complex {
    float real;
    float im;
};

void main() {
    vec2 x = gl_GlobalInvocationID.xy;
    float k = mod(x.y * (float(Size) / pow(2, x.x + 1)), Size);
    complex twiddle = complex(cos(2.0 * PI * k / float(Size)), sin(2.0 * PI * k / float(Size)));

    int butterflyspan = int(pow(2, x.x));
    int butterflywing;
    if (mod(x.y, pow(2, x.x + 1)) < pow(2, x.x)) {
        butterflywing = 1;
    } else {
        butterflywing = 0;
    }

    if (x.x == 0) {
        if (butterflywing == 1) {
            imageStore(PrecomputeBuffer, ivec2(x), vec4(twiddle.real, twiddle.im,
            bit_reversed.j[int(x.y)], bit_reversed.j[int(x.y + 1)]));
        } else {
            imageStore(PrecomputeBuffer, ivec2(x), vec4(twiddle.real, twiddle.im,
            bit_reversed.j[int(x.y - 1)], bit_reversed.j[int(x.y)]));
        }
    } else {
        if (butterflywing == 1) {
            imageStore(PrecomputeBuffer, ivec2(x), vec4(twiddle.real, twiddle.im,
            x.y, x.y + butterflyspan));
        } else {
            imageStore(PrecomputeBuffer, ivec2(x), vec4(twiddle.real, twiddle.im,
            x.y - butterflyspan, x.y));
        }
    }
}
