#version 460 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (binding = 8, rgba32f) writeonly uniform image2D Displacement;
layout (binding = 9, rgba32f) writeonly uniform image2D Derivatives;
layout (binding = 10, rgba32f) uniform image2D Turbulence;

layout (binding = 4, rg32f) readonly uniform image2D Dx_Dz;
layout (binding = 5, rg32f) readonly uniform image2D Dy_Dxz;
layout (binding = 6, rg32f) readonly uniform image2D Dyx_Dyz;
layout (binding = 7, rg32f) readonly uniform image2D Dxx_Dzz;

layout (location = 5) uniform float Lambda;

layout(std140, binding = 2) uniform Environment {
    vec3 sun_color;
    float _pad1;
    vec3 sun_direction;
    float _pad2;
    vec2 wind_velocity;
    float wind_speed;
    float delta_time;
} environment;

void main() {
    uvec2 id = gl_GlobalInvocationID.xy;
    vec2 DxDz = imageLoad(Dx_Dz, ivec2(id)).xy;
    vec2 DyDxz = imageLoad(Dy_Dxz, ivec2(id)).xy;
    vec2 DyxDyz = imageLoad(Dyx_Dyz, ivec2(id)).xy;
    vec2 DxxDzz = imageLoad(Dxx_Dzz, ivec2(id)).xy;

    vec3 displacement = vec3(Lambda * DxDz.x, DyDxz.x, Lambda * DxDz.y);
    imageStore(Displacement, ivec2(id), vec4(displacement, 1.0));

    vec4 derivatives = vec4(DyxDyz, DxxDzz * Lambda);
    imageStore(Derivatives, ivec2(id), derivatives);

    float jacobian = (1.0 + Lambda * DxxDzz.x) * (1.0 + Lambda * DxxDzz.y) - Lambda * Lambda * DyDxz.y * DyDxz.y;
    vec4 turbulence = imageLoad(Turbulence, ivec2(id));
    turbulence.r += environment.delta_time * 0.5 / max(jacobian, 0.5);
    turbulence.r = min(jacobian, turbulence.r);
    imageStore(Turbulence, ivec2(id), turbulence);
}
