#ifndef WIREBOUNDWORLDCREATOR_SRC_VBOS_ALLVBOS_H_
#define WIREBOUNDWORLDCREATOR_SRC_VBOS_ALLVBOS_H_

#include "UiDataInstanced.h"
#include "UiDataMain.h"
#include "UiDataText.h"

#endif  // WIREBOUNDWORLDCREATOR_SRC_VBOS_ALLVBOS_H_
