#ifndef WIREBOUNDWORLDCREATOR_SRC_COMMON_VBOS_H_
#define WIREBOUNDWORLDCREATOR_SRC_COMMON_VBOS_H_

#include <array>

#include "Details.h"

class UiBase;

namespace data {

enum class UiId {
  kMenuTerrain,
  kMenuTerrainOff,
  kMenuTerrainOn1,
  kMenuTerrainOn2,
  kMenuTerrainOn3,

  kMenuWater,
  kMenuWaterOff,
  kMenuWaterOn1,
  kMenuWaterOn2,
  kMenuWaterOn3,

  kMenuRoads,
  kMenuRoadsOff,
  kMenuRoadsOn1,
  kMenuRoadsOn2,
  kMenuRoadsOn3,

  kMenuFences,
  kMenuFencesOff,
  kMenuFencesOn1,
  kMenuFencesOn2,
  kMenuFencesOn3,

  kMenuPlacement,
  kMenuPlacementOff,
  kMenuPlacementOn1,
  kMenuPlacementOn2,
  kMenuPlacementOn3,

  kMenuObjects,
  kMenuObjectsOff,
  kMenuObjectsOn1,
  kMenuObjectsOn2,
  kMenuObjectsOn3,

  kMenuBiomes,
  kMenuBiomesOff,
  kMenuBiomesOn1,
  kMenuBiomesOn2,
  kMenuBiomesOn3,

  kMenuTiles,
  kMenuTilesOff,
  kMenuTilesOn1,
  kMenuTilesOn2,
  kMenuTilesOn3,

  kMenuPlayer,
  kMenuPlayerOff,
  kMenuPlayerOn1,
  kMenuPlayerOn2,
  kMenuPlayerOn3,

  kMenuShaderWirebound,
  kMenuShadersOff,
  kMenuShadersOn1,
  kMenuShadersOn2,
  kMenuShadersOn3,

  kMenuDesk,
  kMenuDeskPinBack,
  kMenuDeskPinPoint,
  kMenuArrowSelect,
  kMenuArrowSelected,

  kMenuSave,
  kMenuLoad,

  kModeModeText,

  kPressedKey,

  kSettingsDesk,
  kSettingsDeskPinBack,
  kSettingsDeskPinPoint,

  kSettingsResolutionLabel,
  kSettingsResolutionLeft,
  kSettingsResolutionRight,
  kSettingsResolution,
  kSettingsFullScreenOff,
  kSettingsFullScreenOn1,
  kSettingsFullScreenOn2,
  kSettingsFullScreenOn3,

  kSettingsSensitivityArea,
  kSettingsSensitivityHandle,

  kSettingsSoundArea,
  kSettingsSoundHandle,
  kSettingsSoundOff,
  kSettingsSoundOn1,
  kSettingsSoundOn2,
  kSettingsSoundOn3,

  kSettingsMusicArea,
  kSettingsMusicHandle,
  kSettingsMusicOff,
  kSettingsMusicOn1,
  kSettingsMusicOn2,
  kSettingsMusicOn3,

  kSettingsTipInfoLabel,
  kSettingsTipInfo,
  kSettingsTipInfoOff,
  kSettingsTipInfoOn1,
  kSettingsTipInfoOn2,
  kSettingsTipInfoOn3,

  kModeTextBack,
  kModeTextLabel,

  kTerrainTerrainMode,
  kTerrainUpdate,
  kTerrainFlatten,
  kTerrainFlattenOff,
  kTerrainFlattenOn1,
  kTerrainFlattenOn2,
  kTerrainFlattenOn3,

  kTerrainFalloffFill,
  kTerrainFalloffBack,
  kTerrainFalloffIcon,

  kTerrainBake,
  kTerrainReset,

  kTerrainBakeDesk,
  kTerrainBakeDeskPinBack,
  kTerrainBakeDeskPinPoint,
  kTerrainBakeAccept,
  kTerrainBakeErosionStepLabel,
  kTerrainBakeErosionStepInputText,
  kTerrainBakeErosionStepInputBack,
  kTerrainBakeWeatheringStepLabel,
  kTerrainBakeWeatheringStepInputText,
  kTerrainBakeWeatheringStepInputBack,
  kTerrainBakeHmap,
  kTerrainBakeHmapName,

  kTerrainEditDesk,
  kTerrainEditDeskPinBack,
  kTerrainEditDeskPinPoint,
  kTerrainEditAccept,
  kTerrainEditName,
  kTerrainEditNameBack,
  kTerrainColorPaletteHS,
  kTerrainColorPaletteB,
  kTerrainColorIndicator,
  kTerrainColorBrightnessCursor,
  kTerrainColorColorCursor,
  kTerrainEditHeightmap,
  kTerrainEditRandomGeneration,

  kTerrainEditLabelInvert,
  kTerrainEditLabelTiling,
  kTerrainEditLabelStrength,

  kTerrainEditTranslateLabel,
  kTerrainEditTranslateXText,
  kTerrainEditTranslateXTextSlot,
  kTerrainEditTranslateYText,
  kTerrainEditTranslateYTextSlot,
  kTerrainEditTranslateZText,
  kTerrainEditTranslateZTextSlot,

  kTerrainEditScaleLabel,
  kTerrainEditScaleXText,
  kTerrainEditScaleXTextSlot,
  kTerrainEditScaleYText,
  kTerrainEditScaleYTextSlot,
  kTerrainEditScaleZText,
  kTerrainEditScaleZTextSlot,

  kTerrainEditRotateLabel,
  kTerrainEditRotateXText,
  kTerrainEditRotateXTextSlot,
  kTerrainEditRotateYText,
  kTerrainEditRotateYTextSlot,
  kTerrainEditRotateZText,
  kTerrainEditRotateZTextSlot,

  kTerrainEditNoiseConfig,
  kTerrainEditNoiseName,
  kTerrainEditNoiseInvertOff,
  kTerrainEditNoiseInvertOn1,
  kTerrainEditNoiseInvertOn2,
  kTerrainEditNoiseInvertOn3,
  kTerrainEditNoiseTilingOff,
  kTerrainEditNoiseTilingOn1,
  kTerrainEditNoiseTilingOn2,
  kTerrainEditNoiseTilingOn3,
  kTerrainEditNoiseStrengthArea,
  kTerrainEditNoiseStrengthIcon,
  kTerrainEditNoiseHmap,

  kWaterWaterMode,
  kWaterUpdate,
  kWaterOcean,
  kWaterRiver,
  kWaterSelected,

  kWaterEditDesk,
  kWaterEditDeskPinBack,
  kWaterEditDeskPinPoint,
  kWaterEditAccept,
  kWaterEditName,
  kWaterEditNameBack,
  kWaterColorPaletteHS,
  kWaterColorPaletteB,
  kWaterColorIndicator,
  kWaterColorBrightnessCursor,
  kWaterColorColorCursor,
  kWaterEditRandomGeneration,

  kWaterEditRiverViscosityText,
  kWaterEditRiverViscosityArea,
  kWaterEditRiverViscosityIcon,
  kWaterEditRiverTransparencyText,
  kWaterEditRiverTransparencyArea,
  kWaterEditRiverTransparencyIcon,

  kWaterEditOceanVisibleOff,
  kWaterEditOceanVisibleOn1,
  kWaterEditOceanVisibleOn2,
  kWaterEditOceanVisibleOn3,
  kWaterEditOceanConfig,
  kWaterEditOceanLayerName,

  kPlacementPlacementMode,

  kPlacementTrees,
  kPlacementTreesOff,
  kPlacementTreesOn1,
  kPlacementTreesOn2,
  kPlacementTreesOn3,

  kPlacementBushes,
  kPlacementBushesOff,
  kPlacementBushesOn1,
  kPlacementBushesOn2,
  kPlacementBushesOn3,

  kPlacementTallGrass,
  kPlacementTallGrassOff,
  kPlacementTallGrassOn1,
  kPlacementTallGrassOn2,
  kPlacementTallGrassOn3,

  kPlacementUndergrowth,
  kPlacementUndergrowthOff,
  kPlacementUndergrowthOn1,
  kPlacementUndergrowthOn2,
  kPlacementUndergrowthOn3,

  kPlacementAsphalt,
  kPlacementAsphaltOff,
  kPlacementAsphaltOn1,
  kPlacementAsphaltOn2,
  kPlacementAsphaltOn3,

  kPlacemenGravel,
  kPlacementGravelOff,
  kPlacementGravelOn1,
  kPlacementGravelOn2,
  kPlacementGravelOn3,

  kPlacementSoil,
  kPlacementSoilOff,
  kPlacementSoilOn1,
  kPlacementSoilOn2,
  kPlacementSoilOn3,

  kPlacementSelected,

  kPlacementChangeMode,
  kPlacementDrawOff,
  kPlacementDrawOn1,
  kPlacementDrawOn2,
  kPlacementDrawOn3,

  kObjectsObjectsMode,
  kObjectsEditDesk,
  kObjectsEditDeskPinBack,
  kObjectsEditDeskPinPoint,
  kObjectsEditAccept,
  kObjectsEditName,
  kObjectsEditNameBack,
  kObjectsEditRandomGeneration,

  kObjectsEditModelName,
  kObjectsEditCharacteristicArea,
  kObjectsEditCharacteristicIcon,

  kBiomesBiomesMode,
  kBiomesBiomePoint,

  kBiomesEditDesk,
  kBiomesEditDeskPinBack,
  kBiomesEditDeskPinPoint,
  kBiomesEditAccept,
  kBiomesEditName,
  kBiomesEditNameBack,
  kBiomesColorPaletteHS,
  kBiomesColorPaletteB,
  kBiomesColorIndicator,
  kBiomesColorBrightnessCursor,
  kBiomesColorColorCursor,
  kBiomesEditRandomGeneration,

  kBiomesEditNoiseName,
  kBiomesEditNoiseStrengthArea,
  kBiomesEditNoiseStrengthIcon,

  kTilesTilesMode,
  kTilesLeft,
  kTilesRight,
  kTilesUp,
  kTilesDown,
  kTilesCreate,
  kTilesRemove,

  kPlayerPlayerMode,
  kPlayerHealthPoint,
  kPlayerStaminaPoint,

  kPlayerGameObjInfoDesk,
  kPlayerGameObjInfoPinBack,
  kPlayerGameObjInfoPinPoint,
  kPlayerGameObjInfoEnemy,
  kPlayerGameObjInfoFriend,
  kPlayerGameObjInfoNeutal,
  kPlayerGameObjInfoObstacle,
  kPlayerGameObjInfoName,
  kPlayerGameObjInfoCharacteristic,
  kPlayerGameObjInfoValue,

  kPlayerPhone,
  kPlayerPhoneMap,
  kPlayerMapPlayer,
  kPlayerMapEnemy,
  kPlayerMapFriend,
  kPlayerMapNeutral,
  kPlayerMapObstacle,

  kConfigWindowName,
  kConfigWindowDesk,
  kConfigWindowPinBack,
  kConfigWindowPinPoint,
  kConfigWindowHandler,
  kConfigWindowSlider,
  kConfigWindowSave,
  kConfigWindowSliderText,
  kConfigWindowSliderArea,
  kConfigWindowSliderIcon,

  kSlotsName,
  kSlotsConfig,
  kSlotsVisibleOff,
  kSlotsVisibleOn1,
  kSlotsVisibleOn2,
  kSlotsVisibleOn3,
  kSlotsSlot,
  kSlotsSlotColor,
  kSlotsRemove,
  kSlotsSelected,
  kSlotsHandler,
  kSlotsSlider,
  kSlotsBack,
  kSlotsCreate,

  kMapTomb,
  kMapFlowerRed,
  kMapFlowerWhite,
  kMapFlowerBlue,
  kMapKorn,
  kMapSeed,
  kMapLeaf,
  kMapSelected1,
  kMapSelected2,
  kMapSelected0,
  kMapEdge,

  kCautionDesk,
  kCautionText,

  kConfirmationDesk,
  kConfirmationText,
  kConfirmationAccept,
  kConfirmationDecline,

  kFileDesk,
  kFileQuestion,
  kFileTextLabel,
  kFileTextBack,
  kFileAccept,
  kFileDecline,

  kTipInfoDesk,
  kTipInfoDeskPinBack,
  kTipInfoDeskPinPoint,
  kTipInfoText,

  kError,
  kConsoleText,
  kConsoleBack,

  kShadow,
  kPivot,

  kWireframeWindow,
  kWireframeWindowFrame,
  kWireframeWindowXpos,
  kWireframeWindowXneg,
  kWireframeWindowYpos,
  kWireframeWindowYneg,
  kWireframeWindowZpos,
  kWireframeWindowZneg,

  kTextRendererCursor,
  kTextRendererPrerenderSlot,

  kCursorRectangle,
  kCursorCircle,
  kCursorLasso,
  kCursorTweak,

  kCompass,
  kCompassNorth,
  kCompassSouth,
  kCompassWest,
  kCompassEast,

  kCursorTree,
  kLoading0,
  kLoading1,
  kLoading2,
  kLoading3,
  kLoading4,
  kLoading5,
  kLoading6,
  kLoading7,
  kLoading8,
  kLoading9,
  kLoading10,
  kLogoBig,
  kLogoMedium,
  kLogoSmall,

  kButtonsTextKeys,
  kButtonsTextMods,

  kSelectionSprite,
  kSelectionCircle,

  kSpare1,
  kSpare2,
  kSpare3,
  kSpare4,
  kSpare5,
  kSpare6,
  kSpare7,
  kSpare8,
  kSpare9,
  kSpare10,

  kTotal,
};

enum class SpriteId {
  kMenuTerrain,
  kMenuTerrainOff,
  kMenuTerrainOn1,
  kMenuTerrainOn2,
  kMenuTerrainOn3,

  kMenuWater,
  kMenuWaterOff,
  kMenuWaterOn1,
  kMenuWaterOn2,
  kMenuWaterOn3,

  kMenuRoads,
  kMenuRoadsOff,
  kMenuRoadsOn1,
  kMenuRoadsOn2,
  kMenuRoadsOn3,

  kMenuFences,
  kMenuFencesOff,
  kMenuFencesOn1,
  kMenuFencesOn2,
  kMenuFencesOn3,

  kMenuPlacement,
  kMenuPlacementOff,
  kMenuPlacementOn1,
  kMenuPlacementOn2,
  kMenuPlacementOn3,

  kMenuObjects,
  kMenuObjectsOff,
  kMenuObjectsOn1,
  kMenuObjectsOn2,
  kMenuObjectsOn3,

  kMenuBiomes,
  kMenuBiomesOff,
  kMenuBiomesOn1,
  kMenuBiomesOn2,
  kMenuBiomesOn3,

  kMenuTiles,
  kMenuTilesOff,
  kMenuTilesOn1,
  kMenuTilesOn2,
  kMenuTilesOn3,

  kMenuPlayer,
  kMenuPlayerOff,
  kMenuPlayerOn1,
  kMenuPlayerOn2,
  kMenuPlayerOn3,

  kMenuShaderWirebound,
  kMenuShadersOff,
  kMenuShadersOn1,
  kMenuShadersOn2,
  kMenuShadersOn3,

  kMenuDesk,
  kMenuDeskPinBack,
  kMenuDeskPinPoint,
  kMenuArrowSelect,
  kMenuArrowSelected,

  kMenuSave,
  kMenuLoad,

  kModeModeText,

  kPressedKey,

  kSettingsDesk,
  kSettingsDeskPinBack,
  kSettingsDeskPinPoint,

  kSettingsResolutionLabel,
  kSettingsResolutionLeft,
  kSettingsResolutionRight,
  kSettingsResolution,
  kSettingsFullScreenOff,
  kSettingsFullScreenOn1,
  kSettingsFullScreenOn2,
  kSettingsFullScreenOn3,

  kSettingsSensitivityArea,
  kSettingsSensitivityHandle,

  kSettingsSoundArea,
  kSettingsSoundHandle,
  kSettingsSoundOff,
  kSettingsSoundOn1,
  kSettingsSoundOn2,
  kSettingsSoundOn3,

  kSettingsMusicArea,
  kSettingsMusicHandle,
  kSettingsMusicOff,
  kSettingsMusicOn1,
  kSettingsMusicOn2,
  kSettingsMusicOn3,

  kSettingsTipInfoLabel,
  kSettingsTipInfo,
  kSettingsTipInfoOff,
  kSettingsTipInfoOn1,
  kSettingsTipInfoOn2,
  kSettingsTipInfoOn3,

  kModeTextBack,
  kModeTextLabel,

  kTerrainTerrainMode,
  kTerrainUpdate,
  kTerrainFlatten,
  kTerrainFlattenOff,
  kTerrainFlattenOn1,
  kTerrainFlattenOn2,
  kTerrainFlattenOn3,

  kTerrainFalloffFill,
  kTerrainFalloffBack,
  kTerrainFalloffIcon,

  kTerrainBake,
  kTerrainReset,

  kTerrainBakeDesk,
  kTerrainBakeDeskPinBack,
  kTerrainBakeDeskPinPoint,
  kTerrainBakeAccept,
  kTerrainBakeErosionStepLabel,
  kTerrainBakeErosionStepInputText,
  kTerrainBakeErosionStepInputBack,
  kTerrainBakeWeatheringStepLabel,
  kTerrainBakeWeatheringStepInputText,
  kTerrainBakeWeatheringStepInputBack,
  kTerrainBakeHmap,
  kTerrainBakeHmapName,

  kTerrainEditDesk,
  kTerrainEditDeskPinBack,
  kTerrainEditDeskPinPoint,
  kTerrainEditAccept,
  kTerrainEditName,
  kTerrainEditNameBack,
  kTerrainColorPaletteHS,
  kTerrainColorPaletteB,
  kTerrainColorIndicator,
  kTerrainColorBrightnessCursor,
  kTerrainColorColorCursor,
  kTerrainEditHeightmap,
  kTerrainEditRandomGeneration,

  kTerrainEditLabelInvert,
  kTerrainEditLabelTiling,
  kTerrainEditLabelStrength,

  kTerrainEditTranslateLabel,
  kTerrainEditTranslateXText,
  kTerrainEditTranslateXTextSlot,
  kTerrainEditTranslateYText,
  kTerrainEditTranslateYTextSlot,
  kTerrainEditTranslateZText,
  kTerrainEditTranslateZTextSlot,

  kTerrainEditScaleLabel,
  kTerrainEditScaleXText,
  kTerrainEditScaleXTextSlot,
  kTerrainEditScaleYText,
  kTerrainEditScaleYTextSlot,
  kTerrainEditScaleZText,
  kTerrainEditScaleZTextSlot,

  kTerrainEditRotateLabel,
  kTerrainEditRotateXText,
  kTerrainEditRotateXTextSlot,
  kTerrainEditRotateYText,
  kTerrainEditRotateYTextSlot,
  kTerrainEditRotateZText,
  kTerrainEditRotateZTextSlot,

  kTerrainEditNoiseConfig,
  kTerrainEditNoiseName,
  kTerrainEditNoiseInvertOff,
  kTerrainEditNoiseInvertOn1,
  kTerrainEditNoiseInvertOn2,
  kTerrainEditNoiseInvertOn3,
  kTerrainEditNoiseTilingOff,
  kTerrainEditNoiseTilingOn1,
  kTerrainEditNoiseTilingOn2,
  kTerrainEditNoiseTilingOn3,
  kTerrainEditNoiseStrengthArea,
  kTerrainEditNoiseStrengthIcon,
  kTerrainEditNoiseHmap,

  kWaterWaterMode,
  kWaterUpdate,
  kWaterOcean,
  kWaterRiver,
  kWaterSelected,

  kWaterEditDesk,
  kWaterEditDeskPinBack,
  kWaterEditDeskPinPoint,
  kWaterEditAccept,
  kWaterEditName,
  kWaterEditNameBack,
  kWaterColorPaletteHS,
  kWaterColorPaletteB,
  kWaterColorIndicator,
  kWaterColorBrightnessCursor,
  kWaterColorColorCursor,
  kWaterEditRandomGeneration,

  kWaterEditRiverViscosityText,
  kWaterEditRiverViscosityArea,
  kWaterEditRiverViscosityIcon,
  kWaterEditRiverTransparencyText,
  kWaterEditRiverTransparencyArea,
  kWaterEditRiverTransparencyIcon,

  kWaterEditOceanVisibleOff,
  kWaterEditOceanVisibleOn1,
  kWaterEditOceanVisibleOn2,
  kWaterEditOceanVisibleOn3,
  kWaterEditOceanConfig,
  kWaterEditOceanLayerName,

  kPlacementPlacementMode,

  kPlacementTrees,
  kPlacementTreesOff,
  kPlacementTreesOn1,
  kPlacementTreesOn2,
  kPlacementTreesOn3,

  kPlacementBushes,
  kPlacementBushesOff,
  kPlacementBushesOn1,
  kPlacementBushesOn2,
  kPlacementBushesOn3,

  kPlacementTallGrass,
  kPlacementTallGrassOff,
  kPlacementTallGrassOn1,
  kPlacementTallGrassOn2,
  kPlacementTallGrassOn3,

  kPlacementUndergrowth,
  kPlacementUndergrowthOff,
  kPlacementUndergrowthOn1,
  kPlacementUndergrowthOn2,
  kPlacementUndergrowthOn3,

  kPlacementAsphalt,
  kPlacementAsphaltOff,
  kPlacementAsphaltOn1,
  kPlacementAsphaltOn2,
  kPlacementAsphaltOn3,

  kPlacemenGravel,
  kPlacementGravelOff,
  kPlacementGravelOn1,
  kPlacementGravelOn2,
  kPlacementGravelOn3,

  kPlacementSoil,
  kPlacementSoilOff,
  kPlacementSoilOn1,
  kPlacementSoilOn2,
  kPlacementSoilOn3,

  kPlacementSelected,

  kPlacementChangeMode,
  kPlacementDrawOff,
  kPlacementDrawOn1,
  kPlacementDrawOn2,
  kPlacementDrawOn3,

  kObjectsObjectsMode,
  kObjectsEditDesk,
  kObjectsEditDeskPinBack,
  kObjectsEditDeskPinPoint,
  kObjectsEditAccept,
  kObjectsEditName,
  kObjectsEditNameBack,
  kObjectsEditRandomGeneration,

  kObjectsEditModelName,
  kObjectsEditCharacteristicArea,
  kObjectsEditCharacteristicIcon,

  kBiomesBiomesMode,
  kBiomesBiomePoint,

  kBiomesEditDesk,
  kBiomesEditDeskPinBack,
  kBiomesEditDeskPinPoint,
  kBiomesEditAccept,
  kBiomesEditName,
  kBiomesEditNameBack,
  kBiomesColorPaletteHS,
  kBiomesColorPaletteB,
  kBiomesColorIndicator,
  kBiomesColorBrightnessCursor,
  kBiomesColorColorCursor,
  kBiomesEditRandomGeneration,

  kBiomesEditNoiseName,
  kBiomesEditNoiseStrengthArea,
  kBiomesEditNoiseStrengthIcon,

  kTilesTilesMode,
  kTilesLeft,
  kTilesRight,
  kTilesUp,
  kTilesDown,
  kTilesCreate,
  kTilesRemove,

  kPlayerPlayerMode,
  kPlayerHealthPoint,
  kPlayerStaminaPoint,

  kPlayerGameObjInfoDesk,
  kPlayerGameObjInfoPinBack,
  kPlayerGameObjInfoPinPoint,
  kPlayerGameObjInfoEnemy,
  kPlayerGameObjInfoFriend,
  kPlayerGameObjInfoNeutal,
  kPlayerGameObjInfoObstacle,
  kPlayerGameObjInfoName,
  kPlayerGameObjInfoCharacteristic,
  kPlayerGameObjInfoValue,

  kPlayerPhone,
  kPlayerPhoneMap,
  kPlayerMapPlayer,
  kPlayerMapEnemy,
  kPlayerMapFriend,
  kPlayerMapNeutral,
  kPlayerMapObstacle,

  kConfigWindowName,
  kConfigWindowDesk,
  kConfigWindowPinBack,
  kConfigWindowPinPoint,
  kConfigWindowHandler,
  kConfigWindowSlider,
  kConfigWindowSave,
  kConfigWindowSliderText,
  kConfigWindowSliderArea,
  kConfigWindowSliderIcon,

  kSlotsName,
  kSlotsConfig,
  kSlotsVisibleOff,
  kSlotsVisibleOn1,
  kSlotsVisibleOn2,
  kSlotsVisibleOn3,
  kSlotsSlot,
  kSlotsSlotColor,
  kSlotsRemove,
  kSlotsSelected,
  kSlotsHandler,
  kSlotsSlider,
  kSlotsBack,
  kSlotsCreate,

  kMapTomb,
  kMapFlowerRed,
  kMapFlowerWhite,
  kMapFlowerBlue,
  kMapKorn,
  kMapSeed,
  kMapLeaf,
  kMapSelected1,
  kMapSelected2,
  kMapSelected0,
  kMapEdge,

  kCautionDesk,
  kCautionText,

  kConfirmationDesk,
  kConfirmationText,
  kConfirmationAccept,
  kConfirmationDecline,

  kFileDesk,
  kFileQuestion,
  kFileTextLabel,
  kFileTextBack,
  kFileAccept,
  kFileDecline,

  kTipInfoDesk,
  kTipInfoDeskPinBack,
  kTipInfoDeskPinPoint,
  kTipInfoText,

  kError,
  kConsoleText,
  kConsoleBack,

  kShadow,
  kPivot,

  kWireframeWindow,
  kWireframeWindowFrame,
  kWireframeWindowXpos,
  kWireframeWindowXneg,
  kWireframeWindowYpos,
  kWireframeWindowYneg,
  kWireframeWindowZpos,
  kWireframeWindowZneg,

  kTextRendererCursor,
  kTextRendererPrerenderSlot,

  kCursorRectangle,
  kCursorCircle,
  kCursorLasso,
  kCursorTweak,

  kCompass,
  kCompassNorth,
  kCompassSouth,
  kCompassWest,
  kCompassEast,

  kCursorTree,
  kLoading0,
  kLoading1,
  kLoading2,
  kLoading3,
  kLoading4,
  kLoading5,
  kLoading6,
  kLoading7,
  kLoading8,
  kLoading9,
  kLoading10,
  kLogoBig,
  kLogoMedium,
  kLogoSmall,

  kButtonsTextKeys,
  kButtonsTextMods,

  kSelectionSprite,
  kSelectionCircle,

  kSpare1,
  kSpare2,
  kSpare3,
  kSpare4,
  kSpare5,
  kSpare6,
  kSpare7,
  kSpare8,
  kSpare9,
  kSpare10,

  kTotal,
};

struct SpriteTc {
  glm::vec2 lb = glm::vec2(0.0f);
  glm::vec2 rt = glm::vec2(0.0f);
};

/// auto-generated
extern std::array<SpriteTc, static_cast<int>(SpriteId::kTotal)> gUiSprites;

struct UiTransform {
  glm::vec2 position = glm::vec2(0.0f);
  glm::vec2 scale = glm::vec2(1.0f);
  float rotation = 0.0f;
  float pad1_ = 0.0f;
};

/// read / written-to a file
extern std::array<UiTransform, static_cast<int>(UiId::kTotal)> gUiTransform;

}  // namespace data

#endif  // WIREBOUNDWORLDCREATOR_SRC_COMMON_VBOS_H_
