#ifndef WIREBOUNDWORLDCREATOR_SRC_COMMON_VBOS_H_
#define WIREBOUNDWORLDCREATOR_SRC_COMMON_VBOS_H_

#include <array>
#include <cinttypes>

#include "Details.h"
#include "Text.h"

class UiBase;

namespace data {

struct UiData {
  int32_t id;
  std::size_t vbo_offset;
  data::TextId text_id;

  // parent id to take transform from it
  std::size_t parent_id_{0};

  // useful for e.g. slider to update centre/length of interactive area
  UiBase* ui{nullptr};
};

/// related to kUiVboDataMain
enum class VboIdMain {
  kMenuTerrain = details::kIdOffsetUi,
  kMenuTerrainOff,
  kMenuTerrainOn1,
  kMenuTerrainOn2,
  kMenuTerrainOn3,

  kMenuWater,
  kMenuWaterOff,
  kMenuWaterOn1,
  kMenuWaterOn2,
  kMenuWaterOn3,

  kMenuRoads,
  kMenuRoadsOff,
  kMenuRoadsOn1,
  kMenuRoadsOn2,
  kMenuRoadsOn3,

  kMenuFences,
  kMenuFencesOff,
  kMenuFencesOn1,
  kMenuFencesOn2,
  kMenuFencesOn3,

  kMenuPlacement,
  kMenuPlacementOff,
  kMenuPlacementOn1,
  kMenuPlacementOn2,
  kMenuPlacementOn3,

  kMenuObjects,
  kMenuObjectsOff,
  kMenuObjectsOn1,
  kMenuObjectsOn2,
  kMenuObjectsOn3,

  kMenuBiomes,
  kMenuBiomesOff,
  kMenuBiomesOn1,
  kMenuBiomesOn2,
  kMenuBiomesOn3,

  kMenuTiles,
  kMenuTilesOff,
  kMenuTilesOn1,
  kMenuTilesOn2,
  kMenuTilesOn3,

  kMenuShaderWirebound,
  kMenuShadersOff,
  kMenuShadersOn1,
  kMenuShadersOn2,
  kMenuShadersOn3,

  kMenuDesk,
  kMenuDeskPinBack,
  kMenuDeskPinPoint,
  kMenuArrowSelect,
  kMenuArrowSelected,

  kMenuSave,
  kMenuLoad,


  kSettingsDesk,
  kSettingsDeskPinBack,
  kSettingsDeskPinPoint,

  kSettingsResolutionLabel,
  kSettingsResolutionLeft,
  kSettingsResolutionRight,
  kSettingsResolutionSlot,
  kSettingsResolution,
  kSettingsFullScreenOff,
  kSettingsFullScreenOn1,
  kSettingsFullScreenOn2,
  kSettingsFullScreenOn3,

  kSettingsSensitivityIcon,
  kSettingsSensitivityArea,
  kSettingsSensitivityHandle,

  kSettingsKeyboard,

  kSettingsSoundIcon,
  kSettingsSoundArea,
  kSettingsSoundHandle,
  kSettingsSoundOff,
  kSettingsSoundOn1,
  kSettingsSoundOn2,
  kSettingsSoundOn3,

  kSettingsMusicIcon,
  kSettingsMusicArea,
  kSettingsMusicHandle,
  kSettingsMusicOff,
  kSettingsMusicOn1,
  kSettingsMusicOn2,
  kSettingsMusicOn3,

  kSettingsTipInfoLabel,
  kSettingsTipInfo,
  kSettingsTipInfoOff,
  kSettingsTipInfoOn1,
  kSettingsTipInfoOn2,
  kSettingsTipInfoOn3,

  kModeTextBack,
  kModeTextLabel,
  kCompass,
  kCursorTree,
  kCross,
  kLoading0,
  kLoading1,
  kLoading2,
  kLoading3,
  kLoading4,
  kLoading5,
  kLoading6,
  kLoading7,
  kLoading8,
  kLoading9,
  kLoading10,
  kLogoBig,
  kLogoMedium,
  kLogoSmall,

  kTerrainTerrainMode,
  kTerrainUpdate,
  kTerrainFlatten,
  kTerrainFlattenOff,
  kTerrainFlattenOn1,
  kTerrainFlattenOn2,
  kTerrainFlattenOn3,

  kTerrainSizeFill,
  kTerrainSizeBack,
  kTerrainSizeIcon,

  kTerrainFalloffFill,
  kTerrainFalloffBack,
  kTerrainFalloffIcon,

  kTerrainBake,
  kTerrainBakeDesk,
  kTerrainBakeDeskPinBack,
  kTerrainBakeDeskPinPoint,
  kTerrainBakeAccept,
  kTerrainBakeErosionStepLabel,
  kTerrainBakeErosionStepInput,
  kTerrainBakeWeatheringStepLabel,
  kTerrainBakeWeatheringStepInput,
  kTerrainBakeHeightmap,

  kTerrainSlotsName,
  kTerrainSlotsConfig,
  kTerrainVisibleOff,
  kTerrainVisibleOn1,
  kTerrainVisibleOn2,
  kTerrainVisibleOn3,
  kTerrainSlotsSlot,
  kTerrainSlotsSlotColor,
  kTerrainSlotsRemove,
  kTerrainSlotsSelected,
  kTerrainSlotsHandler,
  kTerrainSlotsSlider,
  kTerrainSlotsBack,
  kTerrainSlotsCreate,
  kTerrainSlotsFlipPointEdgeFace_Back,
  kTerrainSlotsFlipPointEdgeFace,

  kTerrainEditDesk,
  kTerrainEditDeskPinBack,
  kTerrainEditDeskPinPoint,
  kTerrainEditAccept,
  kTerrainEditName,
  kTerrainEditNameBack,
  kTerrainColorPaletteHS,
  kTerrainColorPaletteB,
  kTerrainColorIndicator,
  kTerrainColorBrightnessCursor,
  kTerrainColorColorCursor,
  kTerrainEditHeightmap,
  kTerrainEditRandomGeneration,

  kTerrainEditTranslateXText,
  kTerrainEditTranslateYText,
  kTerrainEditTranslateZText,
  kTerrainEditScaleXText,
  kTerrainEditScaleYText,
  kTerrainEditScaleZText,
  kTerrainEditRotateXText,
  kTerrainEditRotateYText,
  kTerrainEditRotateZText,

  kTerrainEditLabelInvert,

  kTerrainEditNoise1Config,
  kTerrainEditNoise1Name,
  kTerrainEditNoise1InvertLabel,
  kTerrainEditNoise1InvertOff,
  kTerrainEditNoise1InvertOn1,
  kTerrainEditNoise1InvertOn2,
  kTerrainEditNoise1InvertOn3,
  kTerrainEditNoise1TilingLabel,
  kTerrainEditNoise1TilingOff,
  kTerrainEditNoise1TilingOn1,
  kTerrainEditNoise1TilingOn2,
  kTerrainEditNoise1TilingOn3,
  kTerrainEditNoise1StrengthText,
  kTerrainEditNoise1StrengthArea,
  kTerrainEditNoise1StrengthIcon,

  kTerrainEditNoise2Config,
  kTerrainEditNoise2Name,
  kTerrainEditNoise2InvertLabel,
  kTerrainEditNoise2InvertOff,
  kTerrainEditNoise2InvertOn1,
  kTerrainEditNoise2InvertOn2,
  kTerrainEditNoise2InvertOn3,
  kTerrainEditNoise2TilingLabel,
  kTerrainEditNoise2TilingOff,
  kTerrainEditNoise2TilingOn1,
  kTerrainEditNoise2TilingOn2,
  kTerrainEditNoise2TilingOn3,
  kTerrainEditNoise2StrengthText,
  kTerrainEditNoise2StrengthArea,
  kTerrainEditNoise2StrengthIcon,

  kTerrainEditNoise3Config,
  kTerrainEditNoise3Name,
  kTerrainEditNoise3InvertLabel,
  kTerrainEditNoise3InvertOff,
  kTerrainEditNoise3InvertOn1,
  kTerrainEditNoise3InvertOn2,
  kTerrainEditNoise3InvertOn3,
  kTerrainEditNoise3TilingLabel,
  kTerrainEditNoise3TilingOff,
  kTerrainEditNoise3TilingOn1,
  kTerrainEditNoise3TilingOn2,
  kTerrainEditNoise3TilingOn3,
  kTerrainEditNoise3StrengthText,
  kTerrainEditNoise3StrengthArea,
  kTerrainEditNoise3StrengthIcon,

  kTerrainEditNoise4Config,
  kTerrainEditNoise4Name,
  kTerrainEditNoise4InvertLabel,
  kTerrainEditNoise4InvertOff,
  kTerrainEditNoise4InvertOn1,
  kTerrainEditNoise4InvertOn2,
  kTerrainEditNoise4InvertOn3,
  kTerrainEditNoise4TilingLabel,
  kTerrainEditNoise4TilingOff,
  kTerrainEditNoise4TilingOn1,
  kTerrainEditNoise4TilingOn2,
  kTerrainEditNoise4TilingOn3,
  kTerrainEditNoise4StrengthText,
  kTerrainEditNoise4StrengthArea,
  kTerrainEditNoise4StrengthIcon,

  kTerrainEditNoise5Config,
  kTerrainEditNoise5Name,
  kTerrainEditNoise5InvertLabel,
  kTerrainEditNoise5InvertOff,
  kTerrainEditNoise5InvertOn1,
  kTerrainEditNoise5InvertOn2,
  kTerrainEditNoise5InvertOn3,
  kTerrainEditNoise5TilingLabel,
  kTerrainEditNoise5TilingOff,
  kTerrainEditNoise5TilingOn1,
  kTerrainEditNoise5TilingOn2,
  kTerrainEditNoise5TilingOn3,
  kTerrainEditNoise5StrengthText,
  kTerrainEditNoise5StrengthArea,
  kTerrainEditNoise5StrengthIcon,

  kTerrainEditNoise6Config,
  kTerrainEditNoise6Name,
  kTerrainEditNoise6InvertLabel,
  kTerrainEditNoise6InvertOff,
  kTerrainEditNoise6InvertOn1,
  kTerrainEditNoise6InvertOn2,
  kTerrainEditNoise6InvertOn3,
  kTerrainEditNoise6TilingLabel,
  kTerrainEditNoise6TilingOff,
  kTerrainEditNoise6TilingOn1,
  kTerrainEditNoise6TilingOn2,
  kTerrainEditNoise6TilingOn3,
  kTerrainEditNoise6StrengthText,
  kTerrainEditNoise6StrengthArea,
  kTerrainEditNoise6StrengthIcon,

  kTerrainEditNoise7Config,
  kTerrainEditNoise7Name,
  kTerrainEditNoise7InvertLabel,
  kTerrainEditNoise7InvertOff,
  kTerrainEditNoise7InvertOn1,
  kTerrainEditNoise7InvertOn2,
  kTerrainEditNoise7InvertOn3,
  kTerrainEditNoise7TilingLabel,
  kTerrainEditNoise7TilingOff,
  kTerrainEditNoise7TilingOn1,
  kTerrainEditNoise7TilingOn2,
  kTerrainEditNoise7TilingOn3,
  kTerrainEditNoise7StrengthText,
  kTerrainEditNoise7StrengthArea,
  kTerrainEditNoise7StrengthIcon,

  kTerrainEditNoise8Config,
  kTerrainEditNoise8Name,
  kTerrainEditNoise8InvertLabel,
  kTerrainEditNoise8InvertOff,
  kTerrainEditNoise8InvertOn1,
  kTerrainEditNoise8InvertOn2,
  kTerrainEditNoise8InvertOn3,
  kTerrainEditNoise8TilingLabel,
  kTerrainEditNoise8TilingOff,
  kTerrainEditNoise8TilingOn1,
  kTerrainEditNoise8TilingOn2,
  kTerrainEditNoise8TilingOn3,
  kTerrainEditNoise8StrengthText,
  kTerrainEditNoise8StrengthArea,
  kTerrainEditNoise8StrengthIcon,

  kTerrainNoisePerlinScaleText,
  kTerrainNoisePerlinScaleArea,
  kTerrainNoisePerlinScaleIcon,
  kTerrainNoisePerlinSeedText,
  kTerrainNoisePerlinSeedArea,
  kTerrainNoisePerlinSeedIcon,

  kTerrainNoiseCellularScaleText,
  kTerrainNoiseCellularScaleArea,
  kTerrainNoiseCellularScaleIcon,
  kTerrainNoiseCellularJitterText,
  kTerrainNoiseCellularJitterArea,
  kTerrainNoiseCellularJitterIcon,
  kTerrainNoiseCellularSeedText,
  kTerrainNoiseCellularSeedArea,
  kTerrainNoiseCellularSeedIcon,

  kTerrainNoiseMetaballsScaleText,
  kTerrainNoiseMetaballsScaleArea,
  kTerrainNoiseMetaballsScaleIcon,
  kTerrainNoiseMetaballsJitterText,
  kTerrainNoiseMetaballsJitterArea,
  kTerrainNoiseMetaballsJitterIcon,
  kTerrainNoiseMetaballsPhaseText,
  kTerrainNoiseMetaballsPhaseArea,
  kTerrainNoiseMetaballsPhaseIcon,
  kTerrainNoiseMetaballsSeedText,
  kTerrainNoiseMetaballsSeedArea,
  kTerrainNoiseMetaballsSeedIcon,

  kTerrainNoiseFbmGridScaleText,
  kTerrainNoiseFbmGridScaleArea,
  kTerrainNoiseFbmGridScaleIcon,
  kTerrainNoiseFbmGridOctavesText,
  kTerrainNoiseFbmGridOctavesArea,
  kTerrainNoiseFbmGridOctavesIcon,
  kTerrainNoiseFbmGridShiftText,
  kTerrainNoiseFbmGridShiftArea,
  kTerrainNoiseFbmGridShiftIcon,
  kTerrainNoiseFbmGridTimeShiftText,
  kTerrainNoiseFbmGridTimeShiftArea,
  kTerrainNoiseFbmGridTimeShiftIcon,
  kTerrainNoiseFbmGridGainText,
  kTerrainNoiseFbmGridGainArea,
  kTerrainNoiseFbmGridGainIcon,
  kTerrainNoiseFbmGridLacunarityText,
  kTerrainNoiseFbmGridLacunarityArea,
  kTerrainNoiseFbmGridLacunarityIcon,
  kTerrainNoiseFbmGridTranslateText,
  kTerrainNoiseFbmGridTranslateArea,
  kTerrainNoiseFbmGridTranslateIcon,
  kTerrainNoiseFbmGridWarpStrengthText,
  kTerrainNoiseFbmGridWarpStrengthArea,
  kTerrainNoiseFbmGridWarpStrengthIcon,
  kTerrainNoiseFbmGridOctaveFactorText,
  kTerrainNoiseFbmGridOctaveFactorArea,
  kTerrainNoiseFbmGridOctaveFactorIcon,
  kTerrainNoiseFbmGridSeedText,
  kTerrainNoiseFbmGridSeedArea,
  kTerrainNoiseFbmGridSeedIcon,

  kTerrainNoiseFbmMultiScaleText,
  kTerrainNoiseFbmMultiScaleArea,
  kTerrainNoiseFbmMultiScaleIcon,
  kTerrainNoiseFbmMultiLacunarityText,
  kTerrainNoiseFbmMultiLacunarityArea,
  kTerrainNoiseFbmMultiLacunarityIcon,
  kTerrainNoiseFbmMultiOctavesText,
  kTerrainNoiseFbmMultiOctavesArea,
  kTerrainNoiseFbmMultiOctavesIcon,
  kTerrainNoiseFbmMultiPhaseText,
  kTerrainNoiseFbmMultiPhaseArea,
  kTerrainNoiseFbmMultiPhaseIcon,
  kTerrainNoiseFbmMultiSeedText,
  kTerrainNoiseFbmMultiSeedArea,
  kTerrainNoiseFbmMultiSeedIcon,

  kTerrainNoiseFbmdPerlinScaleText,
  kTerrainNoiseFbmdPerlinScaleArea,
  kTerrainNoiseFbmdPerlinScaleIcon,
  kTerrainNoiseFbmdPerlinOctavesText,
  kTerrainNoiseFbmdPerlinOctavesArea,
  kTerrainNoiseFbmdPerlinOctavesIcon,
  kTerrainNoiseFbmdPerlinShiftText,
  kTerrainNoiseFbmdPerlinShiftArea,
  kTerrainNoiseFbmdPerlinShiftIcon,
  kTerrainNoiseFbmdPerlinTransformText,
  kTerrainNoiseFbmdPerlinTransformArea,
  kTerrainNoiseFbmdPerlinTransformIcon,
  kTerrainNoiseFbmdPerlinGainText,
  kTerrainNoiseFbmdPerlinGainArea,
  kTerrainNoiseFbmdPerlinGainIcon,
  kTerrainNoiseFbmdPerlinLacunarityText,
  kTerrainNoiseFbmdPerlinLacunarityArea,
  kTerrainNoiseFbmdPerlinLacunarityIcon,
  kTerrainNoiseFbmdPerlinSlopenessText,
  kTerrainNoiseFbmdPerlinSlopenessArea,
  kTerrainNoiseFbmdPerlinSlopenessIcon,
  kTerrainNoiseFbmdPerlinOctaveFactorText,
  kTerrainNoiseFbmdPerlinOctaveFactorArea,
  kTerrainNoiseFbmdPerlinOctaveFactorIcon,
  kTerrainNoiseFbmdPerlinNegativeText,
  kTerrainNoiseFbmdPerlinNegativeOff,
  kTerrainNoiseFbmdPerlinNegativeOn1,
  kTerrainNoiseFbmdPerlinNegativeOn2,
  kTerrainNoiseFbmdPerlinNegativeOn3,
  kTerrainNoiseFbmdPerlinSeedText,
  kTerrainNoiseFbmdPerlinSeedArea,
  kTerrainNoiseFbmdPerlinSeedIcon,

  kTerrainNoiseFbmWarpScaleText,
  kTerrainNoiseFbmWarpScaleArea,
  kTerrainNoiseFbmWarpScaleIcon,
  kTerrainNoiseFbmWarpFactorsText,
  kTerrainNoiseFbmWarpFactorsArea,
  kTerrainNoiseFbmWarpFactorsIcon,
  kTerrainNoiseFbmWarpOctavesText,
  kTerrainNoiseFbmWarpOctavesArea,
  kTerrainNoiseFbmWarpOctavesIcon,
  kTerrainNoiseFbmWarpShiftText,
  kTerrainNoiseFbmWarpShiftArea,
  kTerrainNoiseFbmWarpShiftIcon,
  kTerrainNoiseFbmWarpTimeShiftText,
  kTerrainNoiseFbmWarpTimeShiftArea,
  kTerrainNoiseFbmWarpTimeShiftIcon,
  kTerrainNoiseFbmWarpGainText,
  kTerrainNoiseFbmWarpGainArea,
  kTerrainNoiseFbmWarpGainIcon,
  kTerrainNoiseFbmWarpLacunarityText,
  kTerrainNoiseFbmWarpLacunarityArea,
  kTerrainNoiseFbmWarpLacunarityIcon,
  kTerrainNoiseFbmWarpSlopenessText,
  kTerrainNoiseFbmWarpSlopenessArea,
  kTerrainNoiseFbmWarpSlopenessIcon,
  kTerrainNoiseFbmWarpOctaveFactorText,
  kTerrainNoiseFbmWarpOctaveFactorArea,
  kTerrainNoiseFbmWarpOctaveFactorIcon,
  kTerrainNoiseFbmWarpNegativeText,
  kTerrainNoiseFbmWarpNegativeOff,
  kTerrainNoiseFbmWarpNegativeOn1,
  kTerrainNoiseFbmWarpNegativeOn2,
  kTerrainNoiseFbmWarpNegativeOn3,
  kTerrainNoiseFbmWarpSeedText,
  kTerrainNoiseFbmWarpSeedArea,
  kTerrainNoiseFbmWarpSeedIcon,
  kTerrainNoiseFbmWarpQText,
  kTerrainNoiseFbmWarpQArea,
  kTerrainNoiseFbmWarpQIcon,
  kTerrainNoiseFbmWarpRText,
  kTerrainNoiseFbmWarpRArea,
  kTerrainNoiseFbmWarpRIcon,

  kTerrainNoiseFbmPerlinWarpScaleText,
  kTerrainNoiseFbmPerlinWarpScaleArea,
  kTerrainNoiseFbmPerlinWarpScaleIcon,
  kTerrainNoiseFbmPerlinWarpFactorsText,
  kTerrainNoiseFbmPerlinWarpFactorsArea,
  kTerrainNoiseFbmPerlinWarpFactorsIcon,
  kTerrainNoiseFbmPerlinWarpOctavesText,
  kTerrainNoiseFbmPerlinWarpOctavesArea,
  kTerrainNoiseFbmPerlinWarpOctavesIcon,
  kTerrainNoiseFbmPerlinWarpShiftText,
  kTerrainNoiseFbmPerlinWarpShiftArea,
  kTerrainNoiseFbmPerlinWarpShiftIcon,
  kTerrainNoiseFbmPerlinWarpTimeShiftText,
  kTerrainNoiseFbmPerlinWarpTimeShiftArea,
  kTerrainNoiseFbmPerlinWarpTimeShiftIcon,
  kTerrainNoiseFbmPerlinWarpGainText,
  kTerrainNoiseFbmPerlinWarpGainArea,
  kTerrainNoiseFbmPerlinWarpGainIcon,
  kTerrainNoiseFbmPerlinWarpLacunarityText,
  kTerrainNoiseFbmPerlinWarpLacunarityArea,
  kTerrainNoiseFbmPerlinWarpLacunarityIcon,
  kTerrainNoiseFbmPerlinWarpSlopenessText,
  kTerrainNoiseFbmPerlinWarpSlopenessArea,
  kTerrainNoiseFbmPerlinWarpSlopenessIcon,
  kTerrainNoiseFbmPerlinWarpOctaveFactorText,
  kTerrainNoiseFbmPerlinWarpOctaveFactorArea,
  kTerrainNoiseFbmPerlinWarpOctaveFactorIcon,
  kTerrainNoiseFbmPerlinWarpNegativeText,
  kTerrainNoiseFbmPerlinWarpNegativeOff,
  kTerrainNoiseFbmPerlinWarpNegativeOn1,
  kTerrainNoiseFbmPerlinWarpNegativeOn2,
  kTerrainNoiseFbmPerlinWarpNegativeOn3,
  kTerrainNoiseFbmPerlinWarpSeedText,
  kTerrainNoiseFbmPerlinWarpSeedArea,
  kTerrainNoiseFbmPerlinWarpSeedIcon,
  kTerrainNoiseFbmPerlinWarpQText,
  kTerrainNoiseFbmPerlinWarpQArea,
  kTerrainNoiseFbmPerlinWarpQIcon,
  kTerrainNoiseFbmPerlinWarpRText,
  kTerrainNoiseFbmPerlinWarpRArea,
  kTerrainNoiseFbmPerlinWarpRIcon,


  kWaterWaterMode,
  kWaterUpdate,
  kWaterLake,
  kWaterRiver,
  kWaterWaterfall,

  kWaterSlotsName,
  kWaterSlotsConfig,
  kWaterVisibleOff,
  kWaterVisibleOn1,
  kWaterVisibleOn2,
  kWaterVisibleOn3,
  kWaterSlotsSlot,
  kWaterSlotsSlotColor,
  kWaterSlotsRemove,
  kWaterSlotsSelected,
  kWaterSlotsHandler,
  kWaterSlotsSlider,
  kWaterSlotsBack,
  kWaterSlotsCreate,
  kWaterSlotsFlipPointEdgeFace_Back,
  kWaterSlotsFlipSelectEdit_Back,
  kWaterSlotsFlipPointEdgeFace,
  kWaterSlotsFlipSelectEdit,

  kWaterEditDesk,
  kWaterEditDeskPinBack,
  kWaterEditDeskPinPoint,
  kWaterEditAccept,
  kWaterEditName,
  kWaterEditNameBack,
  kWaterColorPaletteHS,
  kWaterColorPaletteB,
  kWaterColorIndicator,
  kWaterColorBrightnessCursor,
  kWaterColorColorCursor,

  kWaterTypeBack,
  kWaterTypeText,
  kWaterTypePrevious,
  kWaterTypeNext,

  kWaterLayer1,
  kWaterLayer1Window,
  kWaterLayer1PinBack,
  kWaterLayer1PinPoint,
  kWaterLayer1Text,
  kWaterLayer1Off,
  kWaterLayer1On1,
  kWaterLayer1On2,
  kWaterLayer1On3,

  kWater1ScaleLabel,
  kWater1ScaleFill,
  kWater1ScaleBack,
  kWater1ScaleHandler,

  kWater1FetchLabel,
  kWater1FetchFill,
  kWater1FetchBack,
  kWater1FetchHandler,

  kWater1SpreadBlendLabel,
  kWater1SpreadBlendFill,
  kWater1SpreadBlendBack,
  kWater1SpreadBlendHandler,

  kWater1SwellLabel,
  kWater1SwellFill,
  kWater1SwellBack,
  kWater1SwellHandler,

  kWater1PeakEnhancementLabel,
  kWater1PeakEnhancementFill,
  kWater1PeakEnhancementBack,
  kWater1PeakEnhancementHandler,

  kWater1ShortWavesFadeLabel,
  kWater1ShortWavesFadeFill,
  kWater1ShortWavesFadeBack,
  kWater1ShortWavesFadeHandler,

  kWater1LambdaLabel,
  kWater1LambdaFill,
  kWater1LambdaBack,
  kWater1LambdaHandler,


  kWaterLayer2,
  kWaterLayer2Window,
  kWaterLayer2PinBack,
  kWaterLayer2PinPoint,
  kWaterLayer2Text,
  kWaterLayer2Off,
  kWaterLayer2On1,
  kWaterLayer2On2,
  kWaterLayer2On3,

  kWater2ScaleLabel,
  kWater2ScaleFill,
  kWater2ScaleBack,
  kWater2ScaleHandler,

  kWater2FetchLabel,
  kWater2FetchFill,
  kWater2FetchBack,
  kWater2FetchHandler,

  kWater2SpreadBlendLabel,
  kWater2SpreadBlendFill,
  kWater2SpreadBlendBack,
  kWater2SpreadBlendHandler,

  kWater2SwellLabel,
  kWater2SwellFill,
  kWater2SwellBack,
  kWater2SwellHandler,

  kWater2PeakEnhancementLabel,
  kWater2PeakEnhancementFill,
  kWater2PeakEnhancementBack,
  kWater2PeakEnhancementHandler,

  kWater2ShortWavesFadeLabel,
  kWater2ShortWavesFadeFill,
  kWater2ShortWavesFadeBack,
  kWater2ShortWavesFadeHandler,

  kWater2LambdaLabel,
  kWater2LambdaFill,
  kWater2LambdaBack,
  kWater2LambdaHandler,


  kWaterLayer3,
  kWaterLayer3Window,
  kWaterLayer3PinBack,
  kWaterLayer3PinPoint,
  kWaterLayer3Text,
  kWaterLayer3Off,
  kWaterLayer3On1,
  kWaterLayer3On2,
  kWaterLayer3On3,

  kWater3ScaleLabel,
  kWater3ScaleFill,
  kWater3ScaleBack,
  kWater3ScaleHandler,

  kWater3FetchLabel,
  kWater3FetchFill,
  kWater3FetchBack,
  kWater3FetchHandler,

  kWater3SpreadBlendLabel,
  kWater3SpreadBlendFill,
  kWater3SpreadBlendBack,
  kWater3SpreadBlendHandler,

  kWater3SwellLabel,
  kWater3SwellFill,
  kWater3SwellBack,
  kWater3SwellHandler,

  kWater3PeakEnhancementLabel,
  kWater3PeakEnhancementFill,
  kWater3PeakEnhancementBack,
  kWater3PeakEnhancementHandler,

  kWater3ShortWavesFadeLabel,
  kWater3ShortWavesFadeFill,
  kWater3ShortWavesFadeBack,
  kWater3ShortWavesFadeHandler,

  kWater3LambdaLabel,
  kWater3LambdaFill,
  kWater3LambdaBack,
  kWater3LambdaHandler,


  kRoadsRoadsMode,
  kRoadsAsphalt,
  kRoadsGravel,
  kRoadsSoil,

  kRoadsSlotsName,
  kRoadsSlotsConfig,
  kRoadsVisibleOff,
  kRoadsVisibleOn1,
  kRoadsVisibleOn2,
  kRoadsVisibleOn3,
  kRoadsSlotsSlot,
  kRoadsSlotsSlotColor,
  kRoadsSlotsRemove,
  kRoadsSlotsSelected,
  kRoadsSlotsHandler,
  kRoadsSlotsSlider,
  kRoadsSlotsBack,
  kRoadsSlotsCreate,
  kRoadsSlotsFlipPointEdgeFace_Back,
  kRoadsSlotsFlipSelectEdit_Back,
  kRoadsSlotsFlipPointEdgeFace,
  kRoadsSlotsFlipSelectEdit,

  kRoadsEditDesk,
  kRoadsEditPinBack,
  kRoadsEditPinPoint,
  kRoadsEditAccept,
  kRoadsEditName,
  kRoadsEditNameBack,
  kRoadsColorPaletteHS,
  kRoadsColorPaletteB,
  kRoadsColorIndicator,
  kRoadsColorBrightnessCursor,
  kRoadsColorColorCursor,

  kRoadsTypeBack,
  kRoadsTypeText,
  kRoadsTypePrevious,
  kRoadsTypeNext,


  kFencesFencesMode,
  kFencesPicket,
  kFencesChainLink,
  kFencesWooden,

  kFencesSlotsName,
  kFencesSlotsConfig,
  kFencesVisibleOff,
  kFencesVisibleOn1,
  kFencesVisibleOn2,
  kFencesVisibleOn3,
  kFencesSlotsSlot,
  kFencesSlotsSlotColor,
  kFencesSlotsRemove,
  kFencesSlotsSelected,
  kFencesSlotsHandler,
  kFencesSlotsSlider,
  kFencesSlotsBack,
  kFencesSlotsCreate,
  kFencesSlotsFlipPointEdgeFace_Back,
  kFencesSlotsFlipSelectEdit_Back,
  kFencesSlotsFlipPointEdgeFace,
  kFencesSlotsFlipSelectEdit,

  kFencesEditDesk,
  kFencesEditPinBack,
  kFencesEditPinPoint,
  kFencesEditAccept,
  kFencesEditName,
  kFencesEditNameBack,
  kFencesColorPaletteHS,
  kFencesColorPaletteB,
  kFencesColorIndicator,
  kFencesColorBrightnessCursor,
  kFencesColorColorCursor,

  kFencesTypeBack,
  kFencesTypeText,
  kFencesTypePrevious,
  kFencesTypeNext,


  kPlacementPlacementMode,
  kPlacementColorFill,
  kPlacementColorBack,
  kPlacementColorIcon,

  kPlacementSizeFill,
  kPlacementSizeBack,
  kPlacementSizeIcon,

  kPlacementFalloffFill,
  kPlacementFalloffBack,
  kPlacementFalloffIcon,

  kPlacementTrees,
  kPlacementTreesOff,
  kPlacementTreesOn1,
  kPlacementTreesOn2,
  kPlacementTreesOn3,

  kPlacementBushes,
  kPlacementBushesOff,
  kPlacementBushesOn1,
  kPlacementBushesOn2,
  kPlacementBushesOn3,

  kPlacementTallGrass,
  kPlacementTallGrassOff,
  kPlacementTallGrassOn1,
  kPlacementTallGrassOn2,
  kPlacementTallGrassOn3,

  kPlacementUndergrowth,
  kPlacementUndergrowthOff,
  kPlacementUndergrowthOn1,
  kPlacementUndergrowthOn2,
  kPlacementUndergrowthOn3,

  kPlacementChangeMode,

  kPlacementDrawOff,
  kPlacementDrawOn1,
  kPlacementDrawOn2,
  kPlacementDrawOn3,


  kObjectsObjectsMode,
  kObjectsMavka,
  kObjectsVodyaniy,
  kObjectsChugaister,
  kObjectsPedestal,
  kObjectsCampfire,
  kObjectsRoadSign,
  kObjectsHuman,

  kBiomesBiomesMode,

  kBiomesWindDirArea,
  kBiomesWindDirHandle,
  kBiomesWindDirIcon,

  kBiomesSunDirArea,
  kBiomesSunDirHandle,
  kBiomesSunDirIcon,

  kBiomesTimeArea,
  kBiomesTimeHandle,
  kBiomesTimeIcon,

  kBiomesSlotsName,
  kBiomesSlotsConfig,
  kBiomesVisibleOff,
  kBiomesVisibleOn1,
  kBiomesVisibleOn2,
  kBiomesVisibleOn3,
  kBiomesSlotsSlot,
  kBiomesSlotsSlotColor,
  kBiomesSlotsRemove,
  kBiomesSlotsSelected,
  kBiomesSlotsHandler,
  kBiomesSlotsSlider,
  kBiomesSlotsBack,
  kBiomesSlotsCreate,
  kBiomesSlotsFlipPointEdgeFace_Back,
  kBiomesSlotsFlipSelectEdit_Back,
  kBiomesSlotsFlipPointEdgeFace,
  kBiomesSlotsFlipSelectEdit,

  kBiomesEditDesk,
  kBiomesEditPinBack,
  kBiomesEditPinPoint,
  kBiomesEditAccept,
  kBiomesEditName,
  kBiomesEditNameBack,
  kBiomesColorPaletteHS,
  kBiomesColorPaletteB,
  kBiomesColorIndicator,
  kBiomesColorBrightnessCursor,
  kBiomesColorColorCursor,

  kBiomesEditWindFill,
  kBiomesEditWindBack,
  kBiomesEditWindHandler,
  kBiomesEditWindIcon,

  kBiomesEditSunFill,
  kBiomesEditSunBack,
  kBiomesEditSunHandler,
  kBiomesEditSunIcon,

  kBiomesEditTimeFill,
  kBiomesEditTimeBack,
  kBiomesEditTimeHandler,
  kBiomesEditTimeIcon,

  kBiomesEditPrecipitationFill,
  kBiomesEditPrecipitationBack,
  kBiomesEditPrecipitationHandler,
  kBiomesEditPrecipitationIcon,

  kBiomesEditTemperatureFill,
  kBiomesEditTemperatureBack,
  kBiomesEditTemperatureHandler,
  kBiomesEditTemperatureIcon,

  kBiomesEditCloudFill,
  kBiomesEditCloudBack,
  kBiomesEditCloudHandler,
  kBiomesEditCloudIcon,


  kTilesTilesMode,
  kTilesLeft,
  kTilesRight,
  kTilesUp,
  kTilesDown,

  kMapTomb,
  kMapFlowerRed,
  kMapFlowerWhite,
  kMapFlowerBlue,
  kMapKorn,
  kMapSeed,
  kMapLeaf,
  kMapSelected1,
  kMapSelected2,
  kMapSelected0,
  kMapEdge,

  kConfirmationDesk,
  kConfirmationTextLabel,
  kConfirmationAccept,
  kConfirmationDecline,

  kTipInfoDesk,
  kTipInfoDeskPinBack,
  kTipInfoDeskPinPoint,
  kTipInfoText,

  kFileDesk,
  kFileText,
  kFileTextInput,
  kFileAccept,

  kSpareText1,
  kSpareText2,
  kSpareText3,
  kSpareText4,
  kSpareText5,
  kSpareText6,
  kSpareText7,
  kSpareText8,
  kSpareText9,
  kSpareText10,
  kFullScreen,

  kTotal,
};

inline constexpr int gVboIdSize =
    static_cast<int>(VboIdMain::kTotal)
    - static_cast<int>(VboIdMain::kMenuTerrain);

#ifndef NDEBUG

// before RELEASE all transform data should be converted to exact
// coord values, so it would be the same as for all we set kNoTransform

// for each coord we have "in vec3 transform;"
// and we sipmly move it like:
// pos * transform[2] + vec2(transform[0], transform[1])

// for complex ui You should set the same transform,
// so each components has local transform in VboMain.
// This way we can check positions by module without
// adding excessive transform uniform or dependencies

inline constexpr int gUiVboTransformSize = gVboIdSize * 4 * 3;

extern const std::array<float, gUiVboTransformSize> kUiVboDataTransform;

#endif // NDEBUG

inline constexpr std::size_t GetVboMainOffset(VboIdMain id) {
  // for each Ui component 16 floats
  // (4 2d points with position and tex coords)
  return (static_cast<std::size_t>(id) - (details::kIdOffsetUi)) * 4; // TODO: 4?
}

inline UiData GetUiData(VboIdMain btn_type, data::TextId text_id) {
  return {static_cast<int>(btn_type), GetVboMainOffset(btn_type), text_id, 0};
}

// We put all button data to the same vbo buffer;
// here all data for ui inteface. We need only 4
// veftices for GL_DRAW TRIANGLE in order:
// right bottom - right top - left bottom - left top.
// Here for each button we need position and tex coord.
// Because we need it only in 2d, x;y is enought. (u,v fo tex coords)
// Here data represented in such order:
// - btn1 vertex1: x, y, u, v
// - btn1 vertex2: x, y, u, v
// - btn1 vertex3: x, y, u, v
// - btn1 vertex4: x, y, u, v
// - btn2 buttons data...
// This way kUiData can use the same vbo and shader, but
// in case of dynamic position component (like slider) we
// need to use another shader (vbo with starting position is the same)
extern const std::array<float, gVboIdSize * 16> kUiVboDataMain;

} // namespace vbos

#endif  // WIREBOUNDWORLDCREATOR_SRC_COMMON_VBOS_H_
